version: "3.5"

services:
  app:
    build:
      context: ./docker/app
      args:
        - PHP_IMAGE=${PHP_IMAGE}
        - APP_DIR=${APP_DIR}
    container_name: app
    user: ${UID}:${GID}
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
      - 8080:8080

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    ports:
      - ${NGINX_PORT}:80
      - 443:443
  

